### ISSUE TITLE
sqlify generates wrong query when using table alias

### ISSUE THREAD

**Issue by helkatz** [taozhi8833998/node-sql-parser#1669] opened 2023-11-20 06:45 UTC
tested on MYSQL 

select * from table1 as t1 join table2 on t1.id=table2.id

**generates with sqlify  the following query**
select * from table1 as t1 join table2 on table1.id=table2.id

this generated sql cannot be executed because it uses not the alias in ON clause

**Comment by taozhi8833998** [comment] 2023-11-20 07:13
@helkatz I can't reproduce it, and test it right [here](https://runkit.com/636d9fb4da573500088dbcc9/655b0650d7a10e0008f4bd34)

<img width="1110" alt="image" src="https://github.com/taozhi8833998/node-sql-parser/assets/7252180/fe52cf68-0192-49d4-8670-cf35b5c268a8">

**Comment by taozhi8833998** [comment] 2023-11-20 07:14
You can upgrade the `node-sql-parser` version to the latest 4.11.0, and try again.

BTW, I will close the issue, if I am wrong, please reopen it, and show the codes and version you are using. Thanks

**Closed by taozhi8833998** 2023-11-20 07:14 UTC
Labels: invalid

**Comment by helkatz** [comment] 2023-11-20 08:13
@taozhi8833998 
Thanks for your fast response!!!
I used already 4.11.0 and strange is now i cannot reproduce it anymore
maybe something wrong on my side
